### PR TITLE
Feature/eslint no usebanner

### PR DESCRIPTION
**Pull request by faceleg**
- Removed usebanner in favour of adding banner on build/minify
 - Removed JSHint in favour of ESLint
<a href='#crh-start'></a><a href='#crh-data-%7B%22approved%22%3A%20%7B%22https%3A//github.com/faceleg%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/1000759%3Fv%3D3%22%7D%2C%20%22https%3A//github.com/rafanami%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/1206450%3Fv%3D3%22%7D%7D%2C%20%22comments%22%3A%20%7B%22General%20Comment%22%3A%20%7B%22html_url%22%3A%20%22https%3A//github.com/solnet-ead/angular_study_phonecatalog/pull/1%23issuecomment-151668503%22%2C%20%22comments%22%3A%20%5B%7B%22body%22%3A%20%22%3Ashipit%3A%22%2C%20%22created_at%22%3A%20%222015-10-27T22%3A53%3A55Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/1000759%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/faceleg%22%7D%7D%2C%20%7B%22body%22%3A%20%22%3Ashipit%3A%22%2C%20%22created_at%22%3A%20%222015-10-27T23%3A14%3A49Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/1206450%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/rafanami%22%7D%7D%2C%20%7B%22body%22%3A%20%22thanks%20%40faceleg%20%20and%20%40rafanami%20for%20your%20participation%20%3A%2B1%3A%20%20it%27s%20good%20to%20solneteers%20here.%22%2C%20%22created_at%22%3A%20%222015-10-28T02%3A19%3A34Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/15221677%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/janeatsolnet%22%7D%7D%5D%2C%20%22title%22%3A%20%22General%20Comment%22%7D%7D%2C%20%22processed%22%3A%20%5B%22https%3A//github.com/solnet-ead/angular_study_phonecatalog/pull/1%23issuecomment-151668503%22%2C%20%22https%3A//github.com/solnet-ead/angular_study_phonecatalog/pull/1%23issuecomment-151672308%22%2C%20%22https%3A//github.com/solnet-ead/angular_study_phonecatalog/pull/1%23issuecomment-151701187%22%5D%7D'></a>
<a href='https://www.codereviewhub.com/'></a>

<a href='https://github.com/faceleg'></a><a href='https://github.com/rafanami'></a>

- [x] <a href='#crh-comment-General Comment'></a> &nbsp;<b><a href='https://github.com/solnet-ead/angular_study_phonecatalog/pull/1#issuecomment-151668503'>General Comment</a></b>
- <a href='https://github.com/faceleg'></a> :shipit:
- <a href='https://github.com/rafanami'></a> :shipit:
- <a href='https://github.com/janeatsolnet'></a> thanks @faceleg  and @rafanami for your participation :+1:  it's good to solneteers here.

<a href='https://www.codereviewhub.com/solnet-ead/angular_study_phonecatalog/pull/1?mark_as_completed=1'></a>&nbsp;<a href='https://www.codereviewhub.com/solnet-ead/angular_study_phonecatalog/pull/1?approve=1'></a>&nbsp;<a href='https://www.codereviewhub.com/solnet-ead/angular_study_phonecatalog/pull/1?approve=0'></a>&nbsp;<a href='https://github.com/solnet-ead/angular_study_phonecatalog/pull/1'></a>
<a href='#crh-end'></a>

### CODE REVIEW

**Comment by igxz** [comment]
This pull request is now managed with CodeReviewHub. <a href='https://github.com/solnet-ead/angular_study_phonecatalog/pull/1'>Refresh</a>.<a href='#crh-update-none'></a>

**Comment by faceleg** [comment]
:shipit:

**Comment by rafanami** [comment]
:shipit:

**Comment by janeatsolnet** [comment]
thanks @faceleg  and @rafanami for your participation :+1:  it's good to solneteers here.

**Comment by igxz** [comment]
@faceleg,  the 'banner' & 'stripBanners' options are really useful, didn't know concat comes with that before. Thanks

**Comment by faceleg** [comment]
:dancer:

**Comment by faceleg** [comment]
It's very easy to miss functionality when reading documentation, and write code / use another module for it. Many times I've done it and later gone back to read the docs for the original module and think waaaaaite a minute...

**Comment by igxz** [comment]
so true.

**Pull request merged**
